brew cask install visual-studio-code
brew cask install slack
brew cask install google-chrome
brew cask install imagealpha
brew cask install imageoptim
brew cask install the-unarchiver
brew cask install keka
brew cask install transmission
brew cask install vlc
brew cask install alfred
brew cask install quickcast
brew cask install monotype-skyfonts
brew cask install google-drive
brew cask install caffeine
brew cask install java
brew cask install flash
brew cask install mailbox
brew cask install eve
brew cask install whiskey
brew cask install coconutbattery
brew cask install plug
brew cask install bartender
brew cask install spotify
brew cask install dashlane
brew cask install typora
brew cask install todoist
brew cask install keepassx
brew cask install virtualbox
brew install docker
brew cask install cyberduck
brew cask install skype
brew cask install screenflow
brew cask install sourcetree
brew cask install charles

